#version: "3.8"
#ADD THIS TO GIT
services: 
  db:
    build: ./requirements/mariadb
    image: mariadb:1.0
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - db_data:/var/lib/mysql
    networks: 
      - inception


  wordpress:
    build: ./requirements/wordpress
    image: wordpress:1.0
    container_name: wordpress
    restart: unless-stopped
    env_file: .env 
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx:1.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html:ro 
    depends_on:
      wordpress:
        condition: service_healthy
    secrets:
      - selfsigned.crt
      - selfsigned.key
    networks:
      - inception



volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME:?error}
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME:?error}

secrets:
  selfsigned.crt:
    file: ${NGINX_SSL_CRT_FILE:?error}
  selfsigned.key:
    file: ${NGINX_SSL_KEY_FILE:?error}

networks:
  inception:
    name: inception


