#version: "3.8"

services: 
  db:
    #image: mariadb:10.5
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql 
    networks: 
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env 
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    #image: nginx:latest
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html:ro 
    depends_on:
      wordpress:
        condition: service_healthy
    secrets:
      - selfsigned.crt
      - selfsigned.key
    networks:
      - inception



volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME:?error}
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME:?error}

networks:
  inception:
    name: inception



secrets:
  selfsigned.crt:
    file: ${NGINX_SSL_CRT_FILE:?error}
  selfsigned.key:
    file: ${NGINX_SSL_KEY_FILE:?error}